<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>DSR - Sreenivasa Vegetable Merchant</title>
<style>
        body {
            font-family: sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
 
        #date {
            position: absolute;
            top: 10px;
            right: 20px;
            font-size: 14px;
        }
 
        h1, h2 {
            text-align: center;
            margin: 10px 0;
        }
 
        h1 {
            color: #007bff; /* Blue */
        }
 
        h2 {
            color: #28a745; /* Green */
        }
 
        .details {
            text-align: center;
            margin-bottom: 20px;
        }
 
        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 20px;
            border: 2px solid #007bff; /* Blue */
            border-radius: 10px;
            max-width: 400px;
            margin: 20px auto;
            background-color: #ffffff;
        }
 
        .input-group {
            margin-bottom: 10px;
            width: 100%;
        }
 
        label {
            display: block;
            margin-bottom: 5px;
        }
 
        input[type="text"],
        input[type="number"] {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
 
        button {
            background-color: #28a745; /* Green */
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
            margin-top: 20px;
            box-sizing: border-box;
        }
 
        /* Responsive Design */
        @media only screen and (max-width: 600px) {
            .container {
                width: 90%;
                padding: 10px;
            }
 
            button {
                padding: 8px 16px;
            }
 
            #date {
                font-size: 12px;
            }
        }
 
        @media only screen and (min-width: 601px) and (max-width: 1200px) {
            .container {
                width: 60%;
            }
        }
</style>
</head>
<body>
<div id="date"></div>
<h1>DSR</h1>
<h2>Sreenivasa Vegetable Merchant</h2>
<div class="details">
<p>Prop: D SURESH REDDY</p>
<p>Phone Numbers: 9000177707, 9848319630, 9885249551</p>
<p>Shop No. 71, Indira Priya Darshini Vegetable Market, Tirupati</p>
</div>
<div class="container">
<div class="input-group">
<label for="customer-name">Customer Name:</label>
<input type="text" id="customer-name">
</div>
<div class="input-group">
<label for="boxes">Number of Boxes:</label>
<input type="number" id="boxes" oninput="calculateAmount()">
</div>
<div class="input-group">
<label for="rate">Rate:</label>
<input type="number" id="rate" oninput="calculateAmount()">
</div>
<div class="input-group">
<label for="amount">Amount:</label>
<input type="text" id="amount" readonly>
</div>
<div class="input-group">
<label for="due">Due:</label>
<input type="number" id="due" oninput="calculateTotal()">
</div>
<div class="input-group">
<label for="total-amount">Total Amount:</label>
<input type="text" id="total-amount" readonly>
</div>
<button id="download-button">Download</button>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>
<script>
        function calculateAmount() {
            const boxes = parseFloat(document.getElementById('boxes').value) || 0;
            const rate = parseFloat(document.getElementById('rate').value) || 0;
            const amount = boxes * rate;
            document.getElementById('amount').value = amount.toFixed(2);
            calculateTotal();
        }
 
        function calculateTotal() {
            const amount = parseFloat(document.getElementById('amount').value) || 0;
            const due = parseFloat(document.getElementById('due').value) || 0;
            const totalAmount = amount + due;
            document.getElementById('total-amount').value = totalAmount.toFixed(2);
        }
 
        document.getElementById('download-button').addEventListener('click', function() {
            const customerName = document.getElementById('customer-name').value;
            const boxes = document.getElementById('boxes').value;
            const rate = document.getElementById('rate').value;
            const amount = document.getElementById('amount').value;
            const due = document.getElementById('due').value;
            const totalAmount = document.getElementById('total-amount').value;
 
            if (!customerName || !boxes || !rate) {
                alert("Please fill out all the required fields.");
                return;
            }
 
            const { jsPDF } = window.jspdf;
            const doc = new jsPDF();
 
            const currentDate = new Date().toLocaleDateString();
 
            // Add content to the PDF
            doc.setFontSize(16);
            doc.text("DSR - Sreenivasa Vegetable Merchant", 10, 10);
            doc.text("Prop: D SURESH REDDY", 10, 20);
            doc.setFontSize(12);
            doc.text("Phone Numbers: 9000177707, 9848319630, 9885249551", 10, 30);
            doc.text("Shop No. 71, Indira Priya Darshini Vegetable Market, Tirupati", 10, 40);
            doc.text("Date: " + currentDate, 150, 40);
            doc.text("Customer Name: " + customerName, 10, 55);
            doc.text("Number of Boxes: " + boxes, 10, 65);
            doc.text("Rate: " + rate, 10, 75);
            doc.text("Amount: " + amount, 10, 85);
            doc.text("Due: " + due, 10, 95);
            doc.text("Total Amount: " + totalAmount, 10, 105);
 
            // Save the PDF
            doc.save("dsr_invoice.pdf");
        });
 
        // Set the current date in the top right corner
        window.onload = function() {
            const currentDate = new Date().toLocaleDateString();
            document.getElementById('date').textContent = "Date: " + currentDate;
        };
</script>
</body>
</html>
